import {test} from 'node:test';import assert from 'node:assert/strict';import {NuvioClient,makeCopyPlan,validatePin,normalizeAddons,discover,settingsBlob,fetchWithTimeout,clone,createId} from '../api.js';
const src={accountId:'master',profileId:'1',addons:[{url:'https://a.test',name:'Custom A',enabled:false},{url:'https://b.test',name:'B',enabled:true}],settings:{features:{player:{language:'hi'}}}};
const dst={accountId:'family',profileId:'1',addons:[{url:'https://a.test/',name:'Old A',enabled:true},{url:'https://c.test',name:'C'}],settings:{features:{layout:{theme:'dark'},player:{language:'en'}}}};
test('merge keeps destination-only addons and copies master names and enabled state without mutating inputs',()=>{const before=structuredClone(dst);const r=makeCopyPlan(src,dst,{addons:true,settings:true});assert.equal(r.addons.length,3);assert.equal(r.addons[0].name,'Custom A');assert.equal(r.addons[0].enabled,false);assert.equal(r.settings.features.player.language,'hi');assert.equal(r.settings.features.layout.theme,'dark');assert.deepEqual(dst,before);});
test('replace removes destination-only addons and uses source order',()=>{const r=makeCopyPlan(src,dst,{addons:true,settings:false,mode:'replace'});assert.deepEqual(r.addons.map(x=>x.url),['https://a.test','https://b.test']);});
test('copy prevents self overwrite and inherited addon writes',()=>{assert.throws(()=>makeCopyPlan(src,src,{addons:true}),/different/);assert.throws(()=>makeCopyPlan(src,{...dst,inherited:true},{addons:true}),/inherits/);});
test('PIN validation preserves leading zero and rejects malformed values',()=>{assert.equal(validatePin('0012'),'0012');for(const value of ['123','12345','abcd','12 3'])assert.throws(()=>validatePin(value));});
test('addon normalization preserves remote order and disabled state',()=>{assert.deepEqual(normalizeAddons([{url:'b',sort_order:1,enabled:false},{url:'a',sort_order:0}]).map(a=>[a.url,a.enabled]),[['a',true],['b',false]]);});
test('API sends destination session and correct settings RPC payload',async()=>{let call;const c=new NuvioClient('https://server.test','public',async(url,init)=>{call={url,init};return new Response('null',{status:200});});c.setSession({access_token:'destination-token',refresh_token:'r'});await c.saveSettings(2,{features:{}});assert.equal(call.init.headers.Authorization,'Bearer destination-token');assert.deepEqual(JSON.parse(call.init.body),{p_profile_id:2,p_settings_json:{features:{}},p_platform:'tv'});});
test('save failure is surfaced rather than reported as saved',async()=>{const c=new NuvioClient('https://server.test','public',async()=>new Response(JSON.stringify({message:'Denied'}),{status:403}));c.setSession({access_token:'a',refresh_token:'r'});await assert.rejects(()=>c.saveAddons(1,[]),/Denied/);});
test('discovery rejects a change to a different server',async()=>{await assert.rejects(()=>discover('https://server.test',async()=>new Response(JSON.stringify({service:'nuvio',publishable_key:'public',backend_url:'https://other.test'}))),/different server/);});
test('settings reject unexpected envelopes',()=>{assert.equal(settingsBlob([{settings_json:{features:{player:{language:'en'}}}}]).features.player.language,'en');assert.throws(()=>settingsBlob({unexpected:true}),/Unsupported/);});

test('login works when AbortSignal.timeout is unavailable in older WebView',async()=>{const original=AbortSignal.timeout;try{AbortSignal.timeout=undefined;const c=new NuvioClient('https://server.test','public',async()=>new Response(JSON.stringify({access_token:'a',refresh_token:'r'})));await c.login('user@example.com','test-password');assert.equal(c.session.accessToken,'a');}finally{AbortSignal.timeout=original;}});
test('legacy WebView clone and account IDs work without newer browser helpers',()=>{const copy=globalThis.structuredClone,uuid=crypto.randomUUID;try{globalThis.structuredClone=undefined;crypto.randomUUID=undefined;const original={addons:[{name:'A'}]};const result=clone(original);result.addons[0].name='B';assert.equal(original.addons[0].name,'A');assert.match(createId(),/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);}finally{globalThis.structuredClone=copy;crypto.randomUUID=uuid;}});
test('connection deadline produces a timeout even for a stalled request',async()=>{await assert.rejects(()=>fetchWithTimeout(()=>new Promise(()=>{}),'https://server.test',{},10),e=>e.name==='TimeoutError');});
test('Nuvio auth msg field is shown to the user',async()=>{const c=new NuvioClient('https://server.test','public',async()=>new Response(JSON.stringify({msg:'Invalid login credentials'}),{status:400}));await assert.rejects(()=>c.login('user@example.com','wrong'),/Invalid login credentials/);});
